export { default as Login } from "../Auth/Login";
export { default as SignUp } from "../Auth/SignUp";
export { default as ForgetPassword } from "../Auth/ForgetPassword";
export { default as ChangePassword } from "../Auth/ChangePassword";
export { default as Profile } from "../Views/Profile/Profile";
export { default as Feed } from "../Views/Feed/Feed";
export { default as Blog } from "../Views/Blog/Blog";
export { default as Tags } from "../Views/Blog/Tags";
export { default as BlogDetail } from "../Views/Blog/BlogDetail";
export { default as Header } from "../Components/Layout/Header";
export { default as EditProfile } from "../Views/Profile/EditProfile";
// export { default as Demo } from "../Views/BlogView/Demo";
